--- FAIL: TestWithoutItem (0.00s)
panic: runtime error: slice bounds out of range [2:1] [recovered]
	panic: runtime error: slice bounds out of range [2:1]

goroutine 21 [running]:
testing.tRunner.func1.2({0x5cd2a0, 0xc0000f0228})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x5cd2a0, 0xc0000f0228})
	/usr/local/go/src/runtime/panic.go:838 +0x207
_/sandbox.withoutItem(...)
	/sandbox/permutations.go:4
_/sandbox.TestWithoutItem(0x0?)
	/sandbox/permutations_test.go:30 +0x210
testing.tRunner(0xc00019a340, 0x5f1990)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL	_/sandbox	0.005s
